[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyside6helpers"
description = "Bits of code used in most PySide based projects"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
authors = [
  {name = "Mr Frangipane", email = "contact@frangipane.me" }
]
maintainers = [
  {name = "Mr Frangipane", email = "contact@frangipane.me" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
]
keywords = ["python", "pyside", "frangitron", "gui"]
dynamic = ["version", "dependencies"]

[tool.setuptools]
include-package-data = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
